-- ============================================
-- Application Météo - Données de test
-- HE-Arc - Services et Composants
-- ============================================
-- Ce script est OPTIONNEL et sert uniquement pour les tests.
-- Les vraies données seront créées via l'application.
-- ============================================

-- Insertion de quelques pays
INSERT INTO PAYS (CODE, NOM) VALUES ('CH', 'Suisse');
INSERT INTO PAYS (CODE, NOM) VALUES ('FR', 'France');
INSERT INTO PAYS (CODE, NOM) VALUES ('DE', 'Allemagne');
INSERT INTO PAYS (CODE, NOM) VALUES ('IT', 'Italie');

-- Insertion de quelques stations de test
-- Note: Les OPENWEATHERMAPID sont des exemples, ils seront remplacés par les vrais IDs lors de l'ajout via l'API
INSERT INTO STATIONMETEO (LATITUDE, LONGITUDE, NOM, NUM_PAYS, OPENWEATHERMAPID) 
VALUES (47.0958, 6.9273, 'La Chaux-de-Fonds', 1, 2660646);

INSERT INTO STATIONMETEO (LATITUDE, LONGITUDE, NOM, NUM_PAYS, OPENWEATHERMAPID) 
VALUES (46.9965, 6.9290, 'Neuchâtel', 1, 2659496);

INSERT INTO STATIONMETEO (LATITUDE, LONGITUDE, NOM, NUM_PAYS, OPENWEATHERMAPID) 
VALUES (46.2044, 6.1432, 'Genève', 1, 2660645);

INSERT INTO STATIONMETEO (LATITUDE, LONGITUDE, NOM, NUM_PAYS, OPENWEATHERMAPID) 
VALUES (48.8566, 2.3522, 'Paris', 2, 2988507);

-- Insertion de quelques mesures de test
-- Station 1 - La Chaux-de-Fonds
INSERT INTO METEO (DATEMESURE, TEMPERATURE, DESCRIPTION, PRESSION, HUMIDITE, VISIBILITE, PRECIPITATION, NUM_STATIONMETEO)
VALUES (SYSDATE - 2, -2.5, 'Neige légère', 1015.0, 85.0, 5000, 2.0, 1);

INSERT INTO METEO (DATEMESURE, TEMPERATURE, DESCRIPTION, PRESSION, HUMIDITE, VISIBILITE, PRECIPITATION, NUM_STATIONMETEO)
VALUES (SYSDATE - 1, -1.0, 'Nuageux', 1018.0, 75.0, 8000, 0.0, 1);

INSERT INTO METEO (DATEMESURE, TEMPERATURE, DESCRIPTION, PRESSION, HUMIDITE, VISIBILITE, PRECIPITATION, NUM_STATIONMETEO)
VALUES (SYSDATE, 1.5, 'Partiellement nuageux', 1020.0, 70.0, 10000, 0.0, 1);

-- Station 2 - Neuchâtel
INSERT INTO METEO (DATEMESURE, TEMPERATURE, DESCRIPTION, PRESSION, HUMIDITE, VISIBILITE, PRECIPITATION, NUM_STATIONMETEO)
VALUES (SYSDATE - 1, 3.0, 'Couvert', 1017.0, 80.0, 7000, 0.5, 2);

INSERT INTO METEO (DATEMESURE, TEMPERATURE, DESCRIPTION, PRESSION, HUMIDITE, VISIBILITE, PRECIPITATION, NUM_STATIONMETEO)
VALUES (SYSDATE, 5.0, 'Ensoleillé', 1022.0, 60.0, 10000, 0.0, 2);

-- Station 3 - Genève
INSERT INTO METEO (DATEMESURE, TEMPERATURE, DESCRIPTION, PRESSION, HUMIDITE, VISIBILITE, PRECIPITATION, NUM_STATIONMETEO)
VALUES (SYSDATE, 8.0, 'Ensoleillé', 1025.0, 55.0, 10000, 0.0, 3);

-- Station 4 - Paris
INSERT INTO METEO (DATEMESURE, TEMPERATURE, DESCRIPTION, PRESSION, HUMIDITE, VISIBILITE, PRECIPITATION, NUM_STATIONMETEO)
VALUES (SYSDATE, 12.0, 'Nuageux', 1010.0, 65.0, 9000, 0.0, 4);

COMMIT;

-- Vérification des données insérées
SELECT 'PAYS: ' || COUNT(*) AS info FROM PAYS
UNION ALL
SELECT 'STATIONS: ' || COUNT(*) FROM STATIONMETEO
UNION ALL
SELECT 'MESURES: ' || COUNT(*) FROM METEO;
