-- ============================================
-- Script de création de la base de données
-- Projet Météo - HE-Arc
-- Ce script peut être exécuté plusieurs fois sans erreur
-- Il supprime et recrée les tables à chaque exécution
-- ============================================

-- Suppression des tables existantes (dans l'ordre des dépendances)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE METEO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE STATIONMETEO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PAYS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- Table PAYS
-- Stocke les informations des pays
CREATE TABLE PAYS (
                      NUMERO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      CODE VARCHAR2(5) NOT NULL UNIQUE,
                      NOM VARCHAR2(100) NOT NULL
);

COMMENT ON TABLE PAYS IS 'Table des pays';
COMMENT ON COLUMN PAYS.NUMERO IS 'Identifiant unique du pays (auto-genere)';
COMMENT ON COLUMN PAYS.CODE IS 'Code ISO du pays (ex: CH, FR, DE)';
COMMENT ON COLUMN PAYS.NOM IS 'Nom complet du pays';

-- Table STATIONMETEO
-- Stocke les stations meteorologiques
CREATE TABLE STATIONMETEO (
                              NUMERO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              LATITUDE NUMBER(10, 6) NOT NULL,
                              LONGITUDE NUMBER(10, 6) NOT NULL,
                              NOM VARCHAR2(200) NOT NULL,
                              NUM_PAYS NUMBER,
                              OPENWEATHERMAPID NUMBER NOT NULL UNIQUE,
                              CONSTRAINT FK_STATION_PAYS FOREIGN KEY (NUM_PAYS) REFERENCES PAYS(NUMERO)
);

COMMENT ON TABLE STATIONMETEO IS 'Table des stations meteorologiques';
COMMENT ON COLUMN STATIONMETEO.NUMERO IS 'Identifiant unique de la station (auto-genere)';
COMMENT ON COLUMN STATIONMETEO.LATITUDE IS 'Latitude GPS de la station';
COMMENT ON COLUMN STATIONMETEO.LONGITUDE IS 'Longitude GPS de la station';
COMMENT ON COLUMN STATIONMETEO.NOM IS 'Nom de la ville/localite';
COMMENT ON COLUMN STATIONMETEO.NUM_PAYS IS 'Reference vers le pays';
COMMENT ON COLUMN STATIONMETEO.OPENWEATHERMAPID IS 'Identifiant unique OpenWeatherMap';

-- Index pour ameliorer les performances
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_STATION_PAYS ON STATIONMETEO(NUM_PAYS)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 THEN RAISE; END IF; END;
/

-- Table METEO
-- Stocke les mesures meteorologiques
CREATE TABLE METEO (
                       NUMERO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       DATEMESURE DATE NOT NULL,
                       TEMPERATURE NUMBER(5, 2) NOT NULL,
                       DESCRIPTION VARCHAR2(200),
                       PRESSION NUMBER(6, 2),
                       HUMIDITE NUMBER(5, 2),
                       VISIBILITE NUMBER(10),
                       PRECIPITATION NUMBER(6, 2),
                       NUM_STATIONMETEO NUMBER NOT NULL,
                       CONSTRAINT FK_METEO_STATION FOREIGN KEY (NUM_STATIONMETEO) REFERENCES STATIONMETEO(NUMERO) ON DELETE CASCADE
);

COMMENT ON TABLE METEO IS 'Table des mesures meteorologiques';
COMMENT ON COLUMN METEO.NUMERO IS 'Identifiant unique de la mesure (auto-genere)';
COMMENT ON COLUMN METEO.DATEMESURE IS 'Date et heure de la mesure';
COMMENT ON COLUMN METEO.TEMPERATURE IS 'Temperature en degres Celsius';
COMMENT ON COLUMN METEO.DESCRIPTION IS 'Description textuelle du temps (ex: nuageux, ensoleille)';
COMMENT ON COLUMN METEO.PRESSION IS 'Pression atmospherique en hPa';
COMMENT ON COLUMN METEO.HUMIDITE IS 'Humidite relative en pourcentage';
COMMENT ON COLUMN METEO.VISIBILITE IS 'Visibilite en metres';
COMMENT ON COLUMN METEO.PRECIPITATION IS 'Precipitations en mm';
COMMENT ON COLUMN METEO.NUM_STATIONMETEO IS 'Reference vers la station';

-- Index pour ameliorer les performances
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_METEO_STATION ON METEO(NUM_STATIONMETEO)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_METEO_DATE ON METEO(DATEMESURE)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 THEN RAISE; END IF; END;
/

-- Contrainte d'unicite pour eviter les doublons de mesures
BEGIN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IDX_METEO_UNIQUE ON METEO(NUM_STATIONMETEO, DATEMESURE)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 THEN RAISE; END IF; END;
/

-- Verification de la creation
SELECT table_name FROM user_tables WHERE table_name IN ('PAYS', 'STATIONMETEO', 'METEO') ORDER BY table_name;

COMMIT;

-- FIN DU SCRIPT
